---
title: "Apply Distribution to Bins"
author: "Thomas Castro"
date: "11/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(hrbrthemes)

```

```{r}

distribution_name <- "distribution_5"
distribution_scale <- "1000"

distr <- read_csv(paste0("distributions/",
                         distribution_name,
                         "-",
                         distribution_scale,
                         ".csv"))

# list of bins
scale_x_step <- c("under 15",
                  "15-25",
                  "25-35",
                  "35-50",
                  "50-75",
                  "75-100",
                  "100-125",
                  "125-150",
                  "150-200",
                  "200-250",
                  "250-500",
                  "500+")

```

```{r}

bin <- rep(1:length(scale_x_step), 
           each = ceiling(dim(distr)[1]/length(scale_x_step)))

bin <- bin[1:dim(distr)[1]]

distr <- cbind(distr,
               bin)

distribution <- distr %>% 
  group_by(bin) %>% 
  summarise(yVal = round(mean(yVal))) %>% 
  mutate(xVal = scale_x_step[bin]) %>% 
  select(xVal, yVal)

```

```{r}

# prepare vector with representative samples

d     <- vector()
d_val <- distribution$xVal
d_rep <- distribution$yVal

for (i in 1:length(d_rep)){
  d <- append(d, rep( d_val[i] , d_rep[i]) )
}

d_graph <- tibble(var = d) 

d_graph %>% 
  group_by(var) %>% 
  summarise(n = n()) %>% 
  ggplot(aes(x = factor(var, levels = scale_x_step),
             y = n)) +
  geom_point()

```


```{r}

# apply to a new column

vets <- read_csv("csv_files/veterans_table1.csv")
income <- sample(d, dim(vets)[1], replace = TRUE)

vets <- cbind(vets, income)

```

```{r, fig.width=10, fig.height=4}

vets %>% 
  group_by(income) %>% 
  summarise(n = n()) %>% 
  ggplot(
    aes(x = factor(income, 
               levels = scale_x_step),
        y = n)
    ) +
  geom_bar(stat = "identity") +
  theme_ipsum_ps() +
  labs(title = "Applying distribution to ordered bins",
       subtitle = "Scaled from pre-made distribution",
       x = "annual income, in thousands",
       y = "count of people",
       caption = "This is just test data for code development only")


```


