---
title: "Apply Distribution by Race"
author: "Thomas Castro"
date: "11/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(hrbrthemes)

vets <- read_csv("csv_files/veterans_table1.csv")
races <- c("Asian", "Black", "Hispanic", "Other", "White")

```

```{r}
VID <- vector()
income <- vector()

for (vet_race in 1:5){
  distribution_name <- paste0("distribution_", vet_race)
  distribution_scale <- "1000"
  
  distr <- read_csv(paste0("distributions/",
                           distribution_name,
                           "-",
                           distribution_scale,
                           ".csv"))
  
  # list of bins
  scale_x_step <- c("under 15",
                    "15-25",
                    "25-35",
                    "35-50",
                    "50-75",
                    "75-100",
                    "100-125",
                    "125-150",
                    "150-200",
                    "200-250",
                    "250-500",
                    "500+")
  
  bin <- rep(1:length(scale_x_step), 
             each = ceiling(dim(distr)[1]/length(scale_x_step)))
  
  bin <- bin[1:dim(distr)[1]]
  
  distr <- cbind(distr,
                 bin)
  
  distribution <- distr %>% 
    group_by(bin) %>% 
    summarise(yVal = round(mean(yVal))) %>% 
    mutate(xVal = scale_x_step[bin]) %>% 
    select(xVal, yVal)
  
  # prepare vector with representative samples
  
  d     <- vector()
  d_val <- distribution$xVal
  d_rep <- distribution$yVal
  
  for (i in 1:length(d_rep)){
    d <- append(d, rep( d_val[i] , d_rep[i]) )
  }
  
  VID_by_race <- vets %>% 
    filter(race == races[vet_race])
  VID <- append(VID, VID_by_race$VID)
  income <- append(income, sample(d, 
                                  dim(VID_by_race)[1],
                                  replace = TRUE))
  
}

```


```{r}

# apply to a new column

vets_income <- tibble(VID = VID,
                      income = income)

vets <- left_join(x = vets, 
                  y = vets_income)

```

```{r, fig.width=10, fig.height=4}

vets %>% 
  group_by(race, income) %>% 
  summarise( n = n()) %>% 
  mutate(percent = n / sum(n) * 100) %>% 
  
  ggplot(
    aes(x = factor(income,
                   levels = scale_x_step),
        y = percent,
        fill = race)
    ) +
  geom_bar(stat = "identity") +
  theme_ipsum_ps() +
  labs(title = "Applying distribution to ordered bins",
       subtitle = "Scaled from pre-made distribution",
       x = "annual income, in thousands",
       y = "percent of people",
       caption = "This is just test data for code development only") +
  facet_wrap(~race)


```

```{r}

write_csv(vets, "csv_files/vets_with_different_income_distributions.csv")

```

