---
title: "Place Veterans in Wards"
author: "Thomas Castro"
date: "11/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(hrbrthemes)

set.seed(2021)

```

```{r}

dcpeople <- read_csv('csv_files/dc_people_with_wards.csv')

table(dcpeople$race)
table(dcpeople$ward)

```

```{r}

# add ID to each person

dcpeople <- cbind(tibble(id = sample(100000:999999, dim(dcpeople)[1]) ),
                  dcpeople)

```

https://planning.dc.gov/sites/default/files/dc/sites/op/page_content/attachments/DC%27s%20Veterans.pdf
Veteran Population by Ward
1, 2356
2, 3028
3, 3871
4, 4824
5, 4978
6, 5089
7, 3980
8, 2991

```{r}

vet_by_ward <- c(2356, 3028, 3871, 4824, 4978, 5089, 3980, 2991)

sum(vet_by_ward)

```



https://planning.dc.gov/sites/default/files/dc/sites/op/page_content/attachments/DC_Veterans_Ward%20Data.pdf

Ward, Male, Female
1, 84.7, 15.3
2, 86.8, 13.2
3, 88.2, 11.8
4, 89.1, 10.9
5, 86.0, 14.0
6, 87.8, 12.2
7, 89.2, 10.8
8, 88.6, 11.4

```{r}

male_by_ward <- c(.847, .868, .882, .891, .860, .878, .892, .886)

```

Ward, 18-34 years, 35-54 years, 55-64 years, 65-74 years, 75 years and over
1, 14.9, 31.2, 18.5, 15.2, 20.2
2, 18.3, 23.3, 14.5, 23.0, 20.9
3,  7.4, 17.7,  7.7, 23.3, 43.9
4,  8.3, 25.7, 17.3, 19.5, 29.2
5,  9.2, 25.5, 25.0, 13.6, 26.7
6, 16.2, 33.1, 18.1, 17.1, 15.5
7,  6.9, 26.7, 26.2, 18.8, 21.3
8, 11.6, 28.5, 30.3, 18.4, 11.3

```{r}
ages <- tribble(
  ~ward, ~ages18to34, ~ages35to54, ~ages55to64, ~ages65to74, ~ages75plus,
  1, 14.9, 31.2, 18.5, 15.2, 20.2,
  2, 18.3, 23.3, 14.5, 23.0, 20.9,
  3,  7.4, 17.7,  7.7, 23.3, 43.9,
  4,  8.3, 25.7, 17.3, 19.5, 29.2,
  5,  9.2, 25.5, 25.0, 13.6, 26.7,
  6, 16.2, 33.1, 18.1, 17.1, 15.5,
  7,  6.9, 26.7, 26.2, 18.8, 21.3,
  8, 11.6, 28.5, 30.3, 18.4, 11.3
)
```

White, Black, AIAN, Asian, NH & OPI, Some Other Race Alone, Two or More Races
1, 45.3, 49.9, 0.0, 1.6, 0.0, 1.8, 0.9
2, 80.9, 14.7, 0.0, 1.4, 0.0, 1.8, 1.2
3, 86.4, 10.4, 0.0, 0.3, 0.0, 0.1, 2.9
4, 25.6, 68.7, 0.4, 0.5, 0.0, 3.3, 1.6
5, 21.2, 75.8, 0.0, 0.3, 0.0, 0.4, 2.3
6, 56.5, 38.7, 0.1, 2.4, 0.0, 0.4, 1.9
7,  2.5, 93.2, 0.7, 0.2, 0.0, 0.6, 2.8
8,  9.9, 88.0, 0.7, 0.1, 0.0, 0.8, 0.5

Hispanic/Latino Population (# and %)
Ward, Percentage
1, 9.3,
2, 6.5,
3, 2.4,
4, 6.5,
5, 2.4,
6, 6.1,
7, 2.5,
8, 1.6

```{r}

races <- tribble(
  ~ward, ~white, ~black, ~aian, ~asian, ~nhopi, ~one_other, ~two_other, ~hispanic,
  1, 45.3, 49.9, 0.0, 1.6, 0.0, 1.8, 0.9, 9.3,
  2, 80.9, 14.7, 0.0, 1.4, 0.0, 1.8, 1.2, 6.5,
  3, 86.4, 10.4, 0.0, 0.3, 0.0, 0.1, 2.9, 2.4,
  4, 25.6, 68.7, 0.4, 0.5, 0.0, 3.3, 1.6, 6.5,
  5, 21.2, 75.8, 0.0, 0.3, 0.0, 0.4, 2.3, 2.4,
  6, 56.5, 38.7, 0.1, 2.4, 0.0, 0.4, 1.9, 6.1,
  7,  2.5, 93.2, 0.7, 0.2, 0.0, 0.6, 2.8, 2.5,
  8,  9.9, 88.0, 0.7, 0.1, 0.0, 0.8, 0.5, 1.6
)
```

```{r}

# Make blank tibble for demographics
demographics <- structure(list(id = NA,
                               ward = NA,
                               race = NA, 
                               age_group = NA,
                               sex = NA), 
                          class = "data.frame")

```

```{r}
# Build demographics
for (i in 1:8){
  
  # Sex
  subgroup <- c( rep("Male", male_by_ward[i]*1000), 
                 rep("Female", 1000 - (male_by_ward[i]*1000)))
  sex <- sample(subgroup, vet_by_ward[i], replace = TRUE)
  
  # Age  ages18to34, ~ages35to54, ~ages55to64, ~ages65to74, ~ages75plus
  subgroup <- c( rep("18-34", ages$ages18to34[i] * 10), 
                 rep("35-54", ages$ages35to54[i] * 10), 
                 rep("55-64", ages$ages55to64[i] * 10), 
                 rep("65-74", ages$ages65to74[i] * 10), 
                 rep("75 plus", ages$ages75plus[i] * 10))
  age <- c(sample(subgroup, vet_by_ward[i], replace = TRUE) )


  # Race  ~white, ~black, ~aian, ~asian, ~nhopi, ~one_other, ~two_other, ~hispanic
  subgroup <- c( rep("White",    ceiling(races$white[i]) * vet_by_ward[i]), 
                 rep("Black",    ceiling(races$black[i]) * vet_by_ward[i]), 
                 rep("Hispanic", ceiling(races$hispanic[i]) * vet_by_ward[i]), 
                 rep("Asian",    ceiling(races$asian[i]) * vet_by_ward[i]), 
                 rep("Other",    ceiling((races$aian[i] + 
                                 races$nhopi[i] +
                                 races$one_other[i] +
                                 races$two_other[i]) ) * vet_by_ward[i]) )
  race <- sample(subgroup, vet_by_ward[i])

  # IDs of people in each ward, by race
  white <- dcpeople %>% filter(race == "White",
                               ward == paste0("Ward ", i))
  white <- white$id
  white <- sample(white, sum(race == "White"))
  white <- tibble(id = white,
                  race = rep("White", length(white)))
  
  black <- dcpeople %>% filter(race == "Black",
                               ward == paste0("Ward ", i))
  black <- black$id
  black <- sample(black, sum(race == "Black"))
  black <- tibble(id = black,
                  race = rep("Black", length(black)))
  
  hispanic <- dcpeople %>% filter(race == "Hispanic",
                               ward == paste0("Ward ", i))
  hispanic <- hispanic$id
  hispanic <- sample(hispanic, sum(race == "Hispanic"))
  hispanic <- tibble(id = hispanic,
                  race = rep("Hispanic", length(hispanic)))
  
  asian <- dcpeople %>% filter(race == "Asian",
                               ward == paste0("Ward ", i))
  asian <- asian$id
  asian <- sample(asian, sum(race == "Asian"))
  asian <- tibble(id = asian,
                  race = rep("Asian", length(asian)))
  
  other <- dcpeople %>% filter(race == "Other",
                               ward == paste0("Ward ", i))
  other <- other$id
  other <- sample(other, sum(race == "Other"))
  other <- tibble(id = other,
                  race = rep("Other", length(other)))
  
  subgroup <- rbind(white, black, hispanic, asian, other)
  subgroup <- cbind(subgroup,
                    ward = rep(paste0("Ward ",i), dim(subgroup)[1]),
                               age, 
                               sex)
  
  demographics <- rbind(demographics,
                        subgroup)
  }

```

```{r}

dcpeople <- left_join(x = dcpeople,
                      y = demographics)

```


```{r}

rm(asian, black, hispanic, other, white)
rm(ages, races, subgroup, demographics)
rm(vet_by_ward, male_by_ward)
rm(age, race, sex, i)

```

```{r}

vets <- dcpeople %>% drop_na()

```

```{r}

write.csv(dcpeople, "csv_files/dc_people_with_veterans.csv")
write.csv(vets, "csv_files/dc_people_just_veterans.csv")

```

